import 'package:practice_project/components/constant_component/image_constant.dart';
import 'package:practice_project/model/product_model.dart';

class MyProduct {
  static List<Product> allProduct = [
    Product(
      id: 1,
      image: AppImage.underarmour01Img,
      name: "UnderArmour Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.adidas01Img,
      name: "Adidas Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.converse02Img,
      name: "Converse Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.puma04Img,
      name: "Puma Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Puma",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.nike01Img,
      name: "Nike Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.adidas02Img,
      name: "Adidas Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.converse04Img,
      name: "Converse Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.puma02Img,
      name: "Puma Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Puma",
      quantity: 1,
    ),
  ];

  static List<Product> nikeProduct = [
    Product(
      id: 1,
      image: AppImage.nike01Img,
      name: "Nike Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.nike02Img,
      name: "Nike Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.nike03Img,
      name: "Nike Jordan",
      price: "367.76",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.nike04Img,
      name: "Nike Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.nike05Img,
      name: "Nike Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.nike06Img,
      name: "Nike Air Max",
      price: "897.99",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
  ];

  static List<Product> pumaProduct = [
    Product(
      id: 1,
      image: AppImage.puma01Img,
      name: "Puma Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Nike",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.puma02Img,
      name: "Puma Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Puma",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.puma03Img,
      name: "Puma Jordan",
      price: "367.76",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Puma",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.puma04Img,
      name: "Puma Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Puma",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.puma05Img,
      name: "Puma Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Puma",
      quantity: 1,
    ),
  ];

  static List<Product> converseProduct = [
    Product(
      id: 1,
      image: AppImage.converse01Img,
      name: "Converse Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.converse02Img,
      name: "Converse Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.converse03Img,
      name: "Converse Jordan",
      price: "367.76",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.converse04Img,
      name: "Converse Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.converse05Img,
      name: "Converse Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Converse",
      quantity: 1,
    ),
  ];

  static List<Product> adidasProduct = [
    Product(
      id: 1,
      image: AppImage.adidas01Img,
      name: "Adidas Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.adidas02Img,
      name: "Adidas Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.adidas03Img,
      name: "Adidas Jordan",
      price: "367.76",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.adidas04Img,
      name: "Adidas Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.adidas05Img,
      name: "Adidas Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "Adidas",
      quantity: 1,
    ),
  ];

  static List<Product> underArmourProduct = [
    Product(
      id: 1,
      image: AppImage.underarmour01Img,
      name: "UnderArmour Club Max",
      price: "478.7",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.underarmour02Img,
      name: "UnderArmour Air Force",
      price: "367.75",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.underarmour03Img,
      name: "UnderArmour Jordan",
      price: "367.76",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.underarmour04Img,
      name: "UnderArmour Air Max",
      price: "254.89",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.underarmour05Img,
      name: "UnderArmour Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.underarmour06Img,
      name: "UnderArmour Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
    Product(
      id: 1,
      image: AppImage.underarmour07Img,
      name: "UnderArmour Air Max",
      price: "571.6",
      description: "Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....",
      brand: "UnderArmour",
      quantity: 1,
    ),
  ];
}
